/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package front_end;

import entity.Thuoc;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utils.DBEngine;
import utils.DataValidation;

/**
 *
 * @author caoba
 */
public class AddThuocView extends javax.swing.JDialog {

    /**
     * Creates new form AddThuocView2
     */
    private QuanLyKhoThuoc home;
    private List<Thuoc> listThuoc;
    private utils.DBEngine controller = new DBEngine();
    
    
    
    public AddThuocView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (QuanLyKhoThuoc) parent;
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm thành viên mới");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtfHanSuDung = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTenThuoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtfNSX = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jcbNhomThuoc = new javax.swing.JComboBox<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtfSoLuong = new javax.swing.JTextPane();
        jtfDangBaoChe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMoTa = new javax.swing.JTextArea();
        jbtThem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtfThanhPhan = new javax.swing.JTextPane();
        jbtHuyBo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Hạn sử dụng");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Tên thuốc");

        jtfHanSuDung.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jScrollPane9.setViewportView(jtfHanSuDung);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Thành phần");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Nhóm thuốc");

        jtfTenThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenThuocActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Dạng bào chế");

        jtfNSX.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jScrollPane10.setViewportView(jtfNSX);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Số lượng");

        jcbNhomThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuốc tim mạch", "Thuốc tiêu hóa", "Thuốc thần kinh", "Thuốc kháng sinh", "Thuốc chống nấm", "Thuốc chống virus", "Thuốc chống ung thư", "Thuốc giảm đau", "Thuốc chống viêm", "Thuốc hạ sốt" }));
        jcbNhomThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNhomThuocActionPerformed(evt);
            }
        });

        jtfSoLuong.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jScrollPane12.setViewportView(jtfSoLuong);

        jtfDangBaoChe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viên", "Nang", "Lọ", "Ống", "mL", "Bình xịt", "Vỉ", "Thuốc mỡ" }));
        jtfDangBaoChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDangBaoCheActionPerformed(evt);
            }
        });

        jtaMoTa.setColumns(20);
        jtaMoTa.setRows(5);
        jScrollPane1.setViewportView(jtaMoTa);

        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jtfThanhPhan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jtfThanhPhan);

        jbtHuyBo.setText("Hủy bỏ");
        jbtHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHuyBoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Mô tả");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Nhà sản xuất");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NHẬP THÔNG TIN THUỐC");
        jLabel1.setToolTipText("<b></b>\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtfTenThuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10)
                            .addComponent(jtfDangBaoChe, javax.swing.GroupLayout.Alignment.TRAILING, 0, 255, Short.MAX_VALUE)
                            .addComponent(jScrollPane12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jcbNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfDangBaoChe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTenThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenThuocActionPerformed

    }//GEN-LAST:event_jtfTenThuocActionPerformed

    private void jcbNhomThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNhomThuocActionPerformed

    }//GEN-LAST:event_jcbNhomThuocActionPerformed

    private void jtfDangBaoCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDangBaoCheActionPerformed

    }//GEN-LAST:event_jtfDangBaoCheActionPerformed
    private static int soThuTu;
    private List<Thuoc> LayFile(String fileName) {
        FileInputStream fi;
        ObjectInputStream in;
        List<Thuoc> list = new ArrayList<>();
        try {
            fi = new FileInputStream(fileName);
            in = new ObjectInputStream(fi);
            list = (ArrayList<Thuoc>) in.readObject();
            fi.close();
            in.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }
  
    private String sinhMaThuoc() {
        List<Thuoc> list = new ArrayList<>();
        list  = LayFile("Thuoc.txt");
        soThuTu=list.size()+1;
        return "MH" + String.format("%02d", soThuTu);
    }
    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed

        String maThuoc = sinhMaThuoc();
        String tenThuoc = jtfTenThuoc.getText().trim();
        String thanhPhan = jtfThanhPhan.getText().trim();
        String hanSuDung = jtfHanSuDung.getText().trim();
        String nhomThuoc = (String) jcbNhomThuoc.getSelectedItem();
        String nhaSanXuat = jtfNSX.getText().trim();
        String soLuongStr = jtfSoLuong.getText().trim();
        String dangBaoChe = (String) jtfDangBaoChe.getSelectedItem();
        String moTa = jtaMoTa.getText().trim();
        if (maThuoc.isEmpty() || tenThuoc.isEmpty() || thanhPhan.isEmpty() || nhomThuoc == null || nhaSanXuat.isEmpty() || soLuongStr.isEmpty() || dangBaoChe == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tất cả các trường bắt buộc", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!DataValidation.DateValidator.isValidDate(hanSuDung)) {
            JOptionPane.showMessageDialog(this, "Hạn sử dụng không hợp lệ. Định dạng đúng: dd/MM/yyyy", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        float soLuong;
        try {
            // Kiểm tra xem soLuongStr có chứa một số hợp lệ hay không
            if (DataValidation.isNumeric(soLuongStr)) {
                throw new NumberFormatException("Số lượng thuốc không hợp lệ");
            }

            soLuong = Float.parseFloat(soLuongStr);
            if (soLuong < 0) {
                throw new NumberFormatException("Số lượng thuốc không được âm");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng thuốc không hợp lệ: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }


        try {
            Thuoc newThuoc = new Thuoc(maThuoc, tenThuoc, thanhPhan, nhomThuoc, nhaSanXuat, soLuong,hanSuDung, dangBaoChe, moTa);
            listThuoc = new ArrayList<>();
            controller.readDataFromFile("Thuoc.txt");
            int ktra = 0;
            for(Thuoc x : listThuoc){
                if(x.getMaThuoc().equals(newThuoc.getMaThuoc())){
                    JOptionPane.showMessageDialog(rootPane, "Ma thuoc da ton tai, Vui long kiem tra lai");
                    ktra  = 1;
                    break;
                }
            }
            if(ktra == 0){
                home.addThuoc(newThuoc);
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công thuốc mới !");
            }
        } catch (Exception e) {
            // Log the exception (if logging is set up in your application)
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm thuốc: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHuyBoActionPerformed
          this.dispose();
    }//GEN-LAST:event_jbtHuyBoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddThuocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddThuocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddThuocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddThuocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddThuocView dialog = new AddThuocView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbtHuyBo;
    private javax.swing.JButton jbtThem;
    private javax.swing.JComboBox<String> jcbNhomThuoc;
    private javax.swing.JTextArea jtaMoTa;
    private javax.swing.JComboBox<String> jtfDangBaoChe;
    private javax.swing.JTextPane jtfHanSuDung;
    private javax.swing.JTextPane jtfNSX;
    private javax.swing.JTextPane jtfSoLuong;
    private javax.swing.JTextField jtfTenThuoc;
    private javax.swing.JTextPane jtfThanhPhan;
    // End of variables declaration//GEN-END:variables
}
